logging:
  level:
    org:
      spring:
        framework: "info"

spring:
  application:
    name: "licensing-service"

  profiles:
    active: "dev"

licensing:
  sku:
    plan1: "TVPXU01"
    plan2: "TVPXU02"
    plan3: "TVPXU01"

