
server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///C:/Learning/spring-microservice-in-action/eagle-eye-config-server/src/main/resources/config/licensing-service/

