tracer:
  property: "Development"


  jpa:
    database: "H2"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"

  datasource:
    driverClassName: org.h2.Driver
    platform: "H2"
    url: "jdbc:h2:mem:eagle_eye_local"
    username: "sa"
    password: ""
    testWhileIdle: "true"
    validationQuery: "SELECT 1"

